name: 02:AWS Infra

on: workflow_dispatch

env:
  TF_VAR_region: "ap-south-1"
  TF_VAR_project_name: ${{ vars.IVS_PROJECT_NAME }}
  TF_VAR_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  TF_VAR_cognito_user_pool_id: ${{ vars.AWS_COGNITO_USER_POOL_ID }}
  TF_VAR_cognito_identity_pool_id: ${{ vars.AWS_COGNITO_IDENTITY_POOL_ID }}
  TF_VAR_cognito_region: ${{ vars.AWS_AMPLIFY_DEPLOYED_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET_FOR_TF_STATE: ${{ secrets.AWS_S3_BUCKET_FOR_TF_STATE }}
  AWS_S3_BUCKET_FOR_TF_STATE_REGION: ${{ vars.AWS_S3_BUCKET_FOR_TF_STATE_REGION }}
  AWS_AMPLIFY_APP_ID: ${{vars.AWS_AMPLIFY_APP_ID}}
  AWS_AMPLIFY_APP_REGION: ${{vars.AWS_AMPLIFY_DEPLOYED_REGION}}
  envVarsPath: ./web-application/.env
  TF_LOG: INFO

jobs:
  terraform_for_infra:
    runs-on: ubuntu-latest
    environment: ivs_inspector_backend

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Setup Terraform with specific version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        id: init
        run: |
          cd terraform-infra
          terraform fmt
          terraform init \
           -backend-config="bucket=$AWS_S3_BUCKET_FOR_TF_STATE" \
           -backend-config="key=infra/$TF_VAR_region/terraform.tfstate" \
           -backend-config="region=$AWS_S3_BUCKET_FOR_TF_STATE_REGION" \
           -reconfigure

      - name: Terraform Validate
        id: validate
        run: |
          cd terraform-infra
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform-infra
          terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: |
          cd terraform-infra
          terraform apply -auto-approve -input=false

      - name: Terraform Output
        id: output
        run: |
          cd terraform-infra
          echo "api_ids=$(terraform output -json api_ids)" >> $GITHUB_OUTPUT

    outputs:
      api_ids: ${{ steps.output.outputs.api_ids }}

  update_amplify_env_vars:
    name: "Adding API IDs into Amplify Env Var"
    runs-on: ubuntu-latest
    environment: ivs_inspector_backend
    needs: terraform_for_infra
    steps:
      - name: Checkout the repositoring to the runner
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_AMPLIFY_APP_REGION

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: 3.9 # Install the python version needed

      - name: Execute Python script # Run the manipulate_apis_vars.py file to manipulate the json
        run: |
          pip install python-dotenv
          current_env_vars=$(aws amplify get-app --app-id $AWS_AMPLIFY_APP_ID | jq '.app.environmentVariables')
          echo $current_env_vars
          api_vars=$(jq --arg region "$TF_VAR_region" '.[$region]' <<< "${{needs.terraform_for_infra.outputs.api_ids}}" | jq '@json')
          echo $api_vars
          # python3 ./workflow-scripts/manipulate_apis_vars.py "$current_env_vars" "$TF_VAR_region" "$api_vars" "$TF_VAR_account_id"
          final_env_var=$(python3 ./workflow-scripts/manipulate_apis_vars.py "$current_env_vars" "VITE_API_${TF_VAR_region}" "$api_vars" "$TF_VAR_account_id")
          aws amplify update-app --app-id $AWS_AMPLIFY_APP_ID --environment-variables "$final_env_var"

  update_webapp_repo_env_vars:
    name: "Adding API IDs into Env Var file"
    runs-on: ubuntu-latest
    environment: ivs_inspector_backend
    needs: update_amplify_env_vars
    steps:
      - name: Checkout the repositoring to the runner
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_AMPLIFY_APP_REGION

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: 3.9 # Install the python version needed

      - name: Execute Python script # Run the manipulate_apis_vars.py file to manipulate the json
        run: |
          pip install python-dotenv
          current_env_vars=$(aws amplify get-app --app-id $AWS_AMPLIFY_APP_ID | jq '.app.environmentVariables')
          python3 ./workflow-scripts/generate.env.py "$current_env_vars"
          mv ./.env $envVarsPath

      - name: Git Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f $envVarsPath
          git commit --allow-empty -m "adding environment variables for localhost access"

      - name: Git Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
